[package]
name = "knapsack-problem"
version = "0.2.0"
authors = ["Marián Hlaváč <hlavac95@gmail.com>"]

[dependencies]
time = "0.1.38"
bit-vec = "0.4.4"
rand = "0.3.18"

[profile.dev]
opt-level = 0
debug = true